"""empty message

Revision ID: cacb69aa5c27
Revises: a942f92694f3
Create Date: 2022-03-01 12:17:25.143037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import spinach.helpers

# revision identifiers, used by Alembic.
revision = 'cacb69aa5c27'
down_revision = 'a942f92694f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #####
    op.create_table('staff_recharge_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('log_datetime', sa.DateTime(), nullable=True),
    sa.Column('op_user_id', sa.Integer(), nullable=True),
    sa.Column('op_username', sa.String(length=100), nullable=True),
    sa.Column('manual_settled', sa.Integer(), nullable=True),
    sa.Column('denied_orders', sa.Integer(), nullable=True),
    sa.Column('average_time_manual_settled', sa.Integer(), nullable=True),
    sa.Column('extra', spinach.helpers.JSONType(), nullable=True),
    sa.ForeignKeyConstraint(['op_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_recharge_daily_created'), 'staff_recharge_daily', ['created'], unique=False)
    op.create_index(op.f('ix_staff_recharge_daily_log_datetime'), 'staff_recharge_daily', ['log_datetime'], unique=False)
    op.create_table('staff_withdrawal_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('log_datetime', sa.DateTime(), nullable=True),
    sa.Column('op_user_id', sa.Integer(), nullable=True),
    sa.Column('op_username', sa.String(length=100), nullable=True),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('total_claim_approve', sa.Integer(), nullable=True),
    sa.Column('total_approved_times', sa.Integer(), nullable=True),
    sa.Column('total_reversed_times', sa.Integer(), nullable=True),
    sa.Column('average_time_claim_approve', sa.Integer(), nullable=True),
    sa.Column('average_time_operation', sa.Integer(), nullable=True),
    sa.Column('total_claim_approve_succeeded', sa.Integer(), nullable=True),
    sa.Column('total_manual_transfer_succeeded', sa.Integer(), nullable=True),
    sa.Column('total_auto_transfer_succeeded', sa.Integer(), nullable=True),
    sa.Column('total_auto_to_manual_transfer_succeeded', sa.Integer(), nullable=True),
    sa.Column('total_transfer_reverse', sa.Integer(), nullable=True),
    sa.Column('average_time_claim_approve_succeeded', sa.Integer(), nullable=True),
    sa.Column('average_time_manual_transfer', sa.Integer(), nullable=True),
    sa.Column('average_time_auto_transfer', sa.Integer(), nullable=True),
    sa.Column('average_time_auto_to_manual_transfer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['op_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_withdrawal_daily_created'), 'staff_withdrawal_daily', ['created'], unique=False)
    op.create_index(op.f('ix_staff_withdrawal_daily_log_datetime'), 'staff_withdrawal_daily', ['log_datetime'], unique=False)
    op.add_column('recharge_stats_daily', sa.Column('average_time_callback', sa.Integer(), server_default='0', nullable=True))
    op.add_column('recharge_stats_daily_multi', sa.Column('average_time_callback', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recharge_stats_daily_multi', 'average_time_callback')
    op.drop_column('recharge_stats_daily', 'average_time_callback')
    op.drop_index(op.f('ix_staff_withdrawal_daily_log_datetime'), table_name='staff_withdrawal_daily')
    op.drop_index(op.f('ix_staff_withdrawal_daily_created'), table_name='staff_withdrawal_daily')
    op.drop_table('staff_withdrawal_daily')
    op.drop_index(op.f('ix_staff_recharge_daily_log_datetime'), table_name='staff_recharge_daily')
    op.drop_index(op.f('ix_staff_recharge_daily_created'), table_name='staff_recharge_daily')
    op.drop_table('staff_recharge_daily')
    # ### end Alembic commands ###
